version: '3.0'

services:
  node:
    build: .
    image: oaw/wcagemtool        
    command: npm start
    restart: always
    container_name: wcag_em_tool_node_2
  
  nginx:
    image: artefactos-ic.scae.redsara.es:6000/nginx:1.13.8-alpine      
    # image: nginx:1.13.8-alpine          
    ports:
      - "1443:443"
    volumes:
      - ./nginx_conf.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/etc/nginx/ssl/server.crt
      - ./server.key:/etc/nginx/ssl/server.key         
    links:
      - node
    restart: always
    shm_size: '1gb'
    container_name: wcag_em_tool_nginx_2
